### ISSUE TITLE
RNEncryptorNative in driod and RNencryptor ios both are same

### ISSUE THREAD

**Issue by smilydronavalli** [RNCryptor/RNCryptor-objc#26] opened 2018-04-30 12:17 UTC
Hi Please
Kindly suggest me driod one image file encrypted using RNencryptorNative that file I will decrypt in RNEncryptor in ios.Is it possible if not why please exaplin

Thanks
Smily

**Comment by rnapier** [comment] 2018-04-30 12:18
Yes. This is possible. The data format is the same. Are you having problems?

**Comment by smilydronavalli** [comment] 2018-04-30 12:24
yes  i will try to decrypt the andriod encrypt image file in ios but the file is not decrypted.please give me solution

**Comment by rnapier** [comment] 2018-04-30 12:32
This isn't enough information to address your problem. I don't know anything about how you're encrypting or decrypting the data, how you're transferring it, or what errors you're receiving. 

Please start with the [FAQ](https://github.com/RNCryptor/RNCryptor#faq) which covers many common errors and understandings. You have likely incorrectly encoded the data during transfer. This is the most common mistake, usually due to base64 encoding the data and then failing to base64 decode the data.

**Comment by smilydronavalli** [comment] 2018-04-30 12:33
In android the code is

  RNCryptorNative.encryptFile(file, fileEcrypted, TableDetailsInfo.Constants.SECURE_PASSWORD);

That encrypted file I will decrypted in ios using the below code

NSString*myPath=[NSString stringWithFormat:@"%@/%@",dataPath,phoOb.imgesOrginal];
        NSData *mydata = [NSData dataWithContentsOfFile:myPath];
        NSData *decryptedData = [RNDecryptor decryptData:mydata withSettings:kRNCryptorAES256Settings password:edKey error:nil];
        UIImage *decimage = [UIImage imageWithData:decryptedData];

But the image is not decrypted,

kindly suggest the solution

**Comment by rnapier** [comment] 2018-04-30 12:38
You've thrown away the error. What error is the system returning? Is the value of `mydata` precisely the same bytes as the contents of `fileEncrypted`?

**Comment by smilydronavalli** [comment] 2018-04-30 12:47
Hi,

I got the following error

ExampleDoc[847:122306] Error Domain=net.robnapier.RNCryptManager Code=2 "Unknown header" UserInfo={NSLocalizedDescription=Unknown header}

**Comment by rnapier** [comment] 2018-04-30 12:57
So that tells you the data you're handing is is not in RNCryptor format. Most likely it's in some encoding like hex or Base64 encoding. The first byte of anything output by RNCryptor will be 0x03.

Go back and make sure that what is written to the file begins with 0x03, and that what you receive on iOS is exactly the same bytes as what you wrote on Android.

**Comment by smilydronavalli** [comment] 2018-04-30 13:04
Hi,

In droid the following code is there

public static void encryptFile(File raw, File encryptedFile, String password) throws IOException {
        byte[] b = readBytes(raw);
        String encodedImage = Base64.encodeToString(b, Base64.DEFAULT);
        byte[] encryptedBytes = new RNCryptorNative().encrypt(encodedImage, password);
        writeBytes(encryptedFile, encryptedBytes);
    }

    /**
     * Decrypts file using password
     * @param encryptedFile file which needs to be decrypted
     * @param result destination file for decrypted file
     * @param password strong generated password
     * @throws IOException
     */
    public static void decryptFile(File encryptedFile, File result, String password) throws IOException {
        byte[] b = readBytes(encryptedFile);
        String decryptedImageString = new RNCryptorNative().decrypt(new String(b), password);
        byte[] decodedBytes = Base64.decode(decryptedImageString, 0);
        writeBytes(result, decodedBytes);
    }


    private static byte[] readBytes(File file){
        int size = (int) file.length();
        byte[] bytes = new byte[size];
        try {
            BufferedInputStream buf = new BufferedInputStream(new FileInputStream(file));
            buf.read(bytes, 0, bytes.length);
            buf.close();
        } catch (FileNotFoundException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        return bytes;
    }

    private static void writeBytes(File file, byte[] bytes) throws IOException{
        BufferedOutputStream bos = new BufferedOutputStream(new FileOutputStream(file));
        bos.write(bytes);
        bos.flush();
        bos.close();
    }

Please tell me how to solve this issue.where the mistake in droid or ios

**Comment by rnapier** [comment] 2018-04-30 13:33
Please look at the file that you've written on Android and the file you're trying to read on iOS. Make sure they are identical and that they both begin with the byte 0x03. That will tell you where the issue is being injected.

**Comment by smilydronavalli** [comment] 2018-05-02 08:51
Hi ,

I am sending Android Encrypted file ,Please tell me how to decrypted that file into iOS.I tried so many ways but i did not get solution .



[Enhanced_Image_2018-04-30_15_31_30.030.txt](https://github.com/RNCryptor/RNCryptor-objc/files/1966536/Enhanced_Image_2018-04-30_15_31_30.030.txt)

**Comment by rnapier** [comment] 2018-05-02 12:29
This data is base-64 encoded. You must base-64 decode it before decrypting it.

If you need live hands-on assistance, I'm available for consulting through codementor:

https://www.codementor.io/robnapier

**Closed as completed** 2018-05-22 18:38 UTC
